config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/login', to: 'sessions#new'
  resources :sessions, only: [:create]
  get '/logout', to: 'sessions#destroy'
  
  get '/', to: 'users#home', as: 'home'
  get '/desserts/top_ten', to: 'desserts#top_ten', as: 'top_ten_desserts'
  get '/meals/top_ten', to: 'meals#top_ten', as: 'top_ten_meals'
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :desserts
  resources :meals
  resources :favorite_desserts, only: [:create, :update]
  resources :favorite_meals, only: [:create, :update]
  
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_one :favorite_dessert 
    has_one :favorite_meal 

    validates :first_name, presence: true 
    validates :last_name, presence: true 
    validates :username, presence: true 
    validates :username, uniqueness: true 
    validates :password, presence: true 

    def full_name 
        self.first_name + " " + self.last_name
    end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController 

    before_action :authentication_required, :current_user, except: [:new, :create]
    before_action :find_user, only: [:edit, :update]

    def new 
        @user = User.new
    end 

    def home 
    end 

    def create 
        @user = User.create(user_params)

        if @user.valid? == true 
            session[:user_id] = @user.id
            redirect_to home_path
        else 
            flash[:errors] = @user.errors.full_messages
            render new_user_path
        end 
    end 

    def show 
    end 

    def edit 
    end 

    def update 
        @user.update(user_params)
        @user.save
        redirect_to user_path(@user)
    end 

    private 

    def find_user
        @user = User.find(params[:id])
    end

    def user_params 
        params.require(:user).permit(:first_name, :last_name, :username, :password)
    end 
end 

app/views/users/edit.html.erb
<br>
<br>
<h1>Edit Page</h1>
<br>
<br>

<%= form_for @user do |f| %>

    <% if flash[:errors] %> 
        <% flash[:errors].each do |error| %>
            <li><%= error %></li>
            <br>
        <% end %> 
    <% end %> 

    <lable>First Name:</lable><br>
    <%= f.text_field :first_name %><br>
    <br>
    <lable>Last Name:</lable><br>
    <%= f.text_field :last_name %><br>
    <br>
    <lable>UserName:</lable><br>
    <%= f.text_field :username %><br>
    <br>
    <lable>Password:</lable><br>
    <%= f.password_field :password %><br>
    <br>
    <lable>Password Confirmation:</lable><br>
    <%= f.password_field :password_confirmation %><br>
    <br>
    <%= f.submit "Update User" %>
    <br>
    <p><%= link_to "Back", user_path(@user) %></p>
<% end %>

app/views/users/home.html.erb
<br>
<br>
<br>

<% if @current_user == User.last %>
    <h1>Welcome to Best Bites, <%= @current_user.first_name%>!</h1>
    <br>
    <p>Best Bites is a simple web app that allows its users to post a favorite meal and dessert, along with their recipes!<br>
    Simply browse through our lists of user-created items and choose what best suits you, OR create your own!<br>
    Then we will see which meals and desserts are most favored in the community!<br>
    Click on any of the tabs above to get started!</p>
<% else %>
    <h1>Welcome back to Best Bites, <%= @current_user.first_name%>!</h1>
    <br>
    <p>We are glad you decided to join us again!<br>
    Click on any of the tabs above to continue!</p>
<% end %>
<br>

app/views/users/new.html.erb
<h1>New User Page</h1>

<%= form_for @user do |f| %>

    <% if flash[:errors] %> 
        <% flash[:errors].each do |error| %>
            <li><%= error %></li>
            <br>
        <% end %> 
    <% end %> 

    <lable>First Name:</lable><br>
    <%= f.text_field :first_name %><br>
    <br>
    <lable>Last Name:</lable><br>
    <%= f.text_field :last_name %><br>
    <br>
    <lable>UserName:</lable><br>
    <%= f.text_field :username %><br>
    <br>
    <lable>Password:</lable><br>
    <%= f.password_field :password %><br>
    <br>
    <lable>Password Confirmation:</lable><br>
    <%= f.password_field :password_confirmation %><br>
    <br>
    <%= f.submit "Create User" %>
    <br>
    <p><%= link_to "Back", login_path %></p>
<% end %>

app/views/users/show.html.erb
<br>
<br>
<br>
<h1><%= @current_user.full_name%></h1>
<br>
<br>
<% if @current_user.favorite_dessert == nil && @current_user.favorite_meal == nil %>
    <p>Oops, looks like your profile is currently empty!<br>
    Click on the 'Desserts' tab or 'Meals' tab to get started!</p>
<% else %>
    <% @fav_dessert=FavoriteDessert.find_by(user_id: @current_user.id)%>
    <% if @current_user.favorite_meal %>
        <% @fav_meal=FavoriteMeal.find_by(user_id: @current_user.id)%>
        <p class="desc"> Your current favorite meal is <%=link_to Meal.find(@fav_meal.meal_id).name, meal_path(Meal.find(@fav_meal.meal_id))%></p>
        <image class="show" src="<%=(url_for(Meal.find(@fav_meal.meal_id).photo))%>"><br><br>
    <% end %>
    <br>
    <br>
    <% if @current_user.favorite_dessert %>
        <% @fav_dessert=FavoriteDessert.find_by(user_id: @current_user.id)%>
        <p class="desc"> Your current favorite dessert is <%=link_to Dessert.find(@fav_dessert.dessert_id).name, dessert_path(Dessert.find(@fav_dessert.dessert_id))%></p>
        <image class="show" src="<%=(url_for(Dessert.find(@fav_dessert.dessert_id).photo))%>"><br><br>
    <% end %>
<% end %>
<br>
<br>
<br>
<h3><%= link_to "Edit Account Info", edit_user_path%></h3>