config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/login', to: 'sessions#new'
  resources :sessions, only: [:create]
  get '/logout', to: 'sessions#destroy'
  
  get '/', to: 'users#home', as: 'home'
  get '/desserts/top_ten', to: 'desserts#top_ten', as: 'top_ten_desserts'
  get '/meals/top_ten', to: 'meals#top_ten', as: 'top_ten_meals'
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :desserts
  resources :meals
  resources :favorite_desserts, only: [:create, :update]
  resources :favorite_meals, only: [:create, :update]
  
end

app/models/meal.rb
class Meal < ApplicationRecord
    has_many :favorite_meals
    has_many :users, through: :favorite_meals
    has_one_attached :photo
    validates :name, presence: true 
    validates :name, uniqueness: true
    validates :recipe, presence: true
    validates :photo, presence: true

    def number_of_favorites
        self.favorite_meals.length
    end 

    def self.h
        h={}
        self.all.each do |meal| 
            h[meal.id]=meal.number_of_favorites
        end 
        #hash keys are dessert_ids and values are num of favorites ordered greatest to least
        h.sort_by {|k,v| -v}
    end 

    def self.top_ten_ids
        ids=self.h.map do |hash_pair|
            hash_pair[0]
        end 
        #only take ten ids
        ids.slice(0,10)
    end 

    def self.top_ten 
        self.top_ten_ids.map do |id| 
            Meal.find(id)
        end 

    end 
   
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
    before_action :authentication_required, :current_user
    before_action :find_meal, only: [:show, :edit, :update, :delete]
    before_action :fav_meal, only: [:new, :show]
    def index 
        @meals=Meal.all
    end 

    def new 
        @meal=Meal.new
    end 

    def show 
        
    end 

    def create 
        
        @meal=Meal.new(meal_params)
        if @meal.valid?
            @meal.save 
            redirect_to meal_path(@meal)
        else 
            render :new
        end 
    end 

     
    def edit 
       
    end 

    def update
        @meal.update(meal_params)
        if @meal.valid?

          redirect_to meal_path(@meal)
        else 
          render :edit 
        end 
    
    end



    def top_ten 
        @top_five=Meal.top_ten.slice(0,5)
        @second_five=Meal.top_ten.slice(5,10)
    end 

    private 
        
        def find_meal
            @meal=Meal.find(params[:id])
        end 

        def meal_params 
            params.require(:meal).permit(:name, :recipe, :photo)
        end 

        def fav_meal
            @fav_meal=FavoriteMeal.find_or_create_by(user_id: session[:user_id])
        end

end 

app/views/meals/_favorite.html.erb
<%= form_for @fav_meal do |f| %> 
    <h2><%=f.label "Favorite?" %></h1> <br>
    <%=f.check_box :meal_id, {}, @meal.id, nil %> 


    <%=f.submit "Favorite this Meal"%>




<% end %> 

app/views/meals/_form.html.erb
<%if @meal.errors %>
    <%@meal.errors.full_messages.each do |message|%>
        <h1 class="error">ERROR: <%=message%></h1>
    <%end%>
<%end%>

<%= form_for @meal do |f| %> 
    <h2><%=f.label :name %></h2> 
    <%=f.text_field :name %> <br><br>

    <h2><%=f.label :photo %></h2> 
    <%=f.file_field :photo %> <br><br>

    <h2><%=f.label :recipe_url %></h2>
    <%=f.text_field :recipe %> <br><br>
    <br>
    <br>

    <%=f.submit %>




<% end %> 

app/views/meals/edit.html.erb
<h1>Edit a Meal</h1><br>
<%= render "form"%>

app/views/meals/index.html.erb
<br>
<br>
<h1> All Meals </h1>
<br>
<ul>
<%@meals.each do |meal|%>
    <li>
        <p><%=link_to meal.name, meal_path(meal)%></p>
    </li>

<%end%>
</ul>
<br>
<br>


<h3 class="create">Don't see your favorite bites listed? Create it <%=link_to "here", new_meal_path%></h3>

app/views/meals/new.html.erb
<br>
<br>
<h1>Create a New Meal</h1><br>
<%= render "form"%>

app/views/meals/show.html.erb
<br>
<br>
<h1><%=@meal.name%></h1><br><br>

<image class="show" src="<%=(url_for(@meal.photo))%>"><br><br>
<h2>Current Favorites: <%=@meal.favorite_meals.length%></h2>

<h1><%=link_to "Recipe", @meal.recipe, target: :_blank%></h1>
<br>
<% if @fav_meal.meal_id==@meal.id%>
    <h1> Delicious! This is your Favorite Meal! </h1><br>
<% else %> 
    <%= render "favorite"%>
<% end%>

app/views/meals/top_ten.html.erb
<br>
<br>
<h1>Top Ten Meals</h1>
<br>
<br>


<div class="row">
<div class="column">
<ol>
<% @top_five.each do |meal|%>
    <li class="bite">
    <image class="top" src="<%=(url_for(meal.photo))%>">
    <h3><%=meal.name%></h3>
    <p><%="#{meal.number_of_favorites} favorites!!!"%></p>
    <p><%= link_to "See #{meal.name}", meal_path(meal)%></p><br><br><br><br>
    </li>
<%end%>
</ol>
</div>
<div class="column">
<% if Meal.top_ten.length >5%>
    <ol start="6">
    <% @second_five.each do |meal|%>
        <li class="bite">
        <image class="top" src="<%=(url_for(meal.photo))%>">
        <h3><%=meal.name%></h3>
        <p><%="#{meal.number_of_favorites} favorites!!!"%></p>
        <p><%= link_to "See #{meal.name}", meal_path(meal)%></p><br><br><br><br>
        </li>
    <%end%>
    </ol>
<%end%>
</div>
</div>