config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/login', to: 'sessions#new'
  resources :sessions, only: [:create]
  get '/logout', to: 'sessions#destroy'
  
  get '/', to: 'users#home', as: 'home'
  get '/desserts/top_ten', to: 'desserts#top_ten', as: 'top_ten_desserts'
  get '/meals/top_ten', to: 'meals#top_ten', as: 'top_ten_meals'
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :desserts
  resources :meals
  resources :favorite_desserts, only: [:create, :update]
  resources :favorite_meals, only: [:create, :update]
  
end

app/models/dessert.rb
class Dessert < ApplicationRecord
    has_many :favorite_desserts 
    has_many :users, through: :favorite_desserts 
    has_one_attached :photo
    validates :name, presence: true 
    validates :name, uniqueness: true
    validates :recipe, presence: true
    validates :photo, presence: true

    def number_of_favorites
        self.favorite_desserts.length
    end 

    def self.hash_desserts 
        h={}
        self.all.each do |dessert| 
            h[dessert.id]=dessert.number_of_favorites
        end 
        #hash keys are dessert_ids and values are num of favorites ordered greatest to least
        h.sort_by {|k,v| -v}
    end 

    def self.top_ten_ids
        ids=self.hash_desserts.map do |hash_pair|
            hash_pair[0]
        end 
        #only take ten ids
        ids.slice(0,10)
    end 

    def self.top_ten 
        self.top_ten_ids.map do |id| 
            Dessert.find(id)
        end 

    end 
   
end

app/controllers/desserts_controller.rb
class DessertsController < ApplicationController
   
    before_action :authentication_required, :current_user
    before_action :find_dessert, only: [:show, :edit, :update, :delete]
    before_action :fav_dessert, only: [:new, :show]
    def index 
        @desserts=Dessert.all
    end 

    def new 
        @dessert=Dessert.new
    end 

    def show 
        
    end 

    def create
        @dessert=Dessert.new(dessert_params)
        if @dessert.valid?
            @dessert.save 
            redirect_to dessert_path(@dessert)
        else 
            render :new
        end 
    end 

   
    def edit 
        
    end 

    def update
        @dessert.update(dessert_params)
        if @dessert.valid?

          redirect_to dessert_path(@dessert)
        else 
          render :edit 
        end 
    
    end

    def top_ten 
        @top_five=Dessert.top_ten.slice(0,5)
        @second_five=Dessert.top_ten.slice(5,10)
    end 

    private 
        
        def find_dessert 
            @dessert=Dessert.find(params[:id])
        end 

        def dessert_params 
            params.require(:dessert).permit(:name, :recipe, :photo)
        end 

        def fav_dessert 
            @fav_dessert=FavoriteDessert.find_or_create_by(user_id: session[:user_id])
        end

end 

app/views/desserts/_favorite.html.erb
<%= form_for @fav_dessert do |f| %> 
    <h2><%=f.label "Favorite?" %></h1> <br>
    <%=f.check_box :dessert_id, {}, @dessert.id, nil %> 


    <%=f.submit "Favorite this Dessert"%>




<% end %> 

app/views/desserts/_form.html.erb
<%if @dessert.errors %>
    <%@dessert.errors.full_messages.each do |message|%>
        <h1 class="error">ERROR: <%=message%></h1>
    <%end%>
<%end%>

<%= form_for @dessert do |f| %> 
    <h2><%=f.label :name %></h2>
    <%=f.text_field :name %> <br><br>

    <h2><%=f.label :photo %></h2>
    <%=f.file_field :photo %> <br><br>

    <h2><%=f.label :recipe_url %></h2> <br>
    <%=f.text_field :recipe %> <br><br>
    <br>
    <br>

    <%=f.submit %>




<% end %> 

app/views/desserts/edit.html.erb
<h1>Edit a Dessert</h1><br>
<%= render "form"%>

app/views/desserts/index.html.erb
<br>
<br>
<h1> All Desserts </h1>
<br>
<br>
<ul>
<%@desserts.each do |dessert|%>
    <li>
        <p><%=link_to dessert.name, dessert_path(dessert)%></p>
    </li>

<%end%>
</ul>
<br>
<br>


<h3 class="create">Don't see your favorite bites listed? Create it <%=link_to "here", new_dessert_path%></h3>

app/views/desserts/new.html.erb
<br>
<br>
<h1>Create a New Dessert</h1><br>
<%= render "form"%>

app/views/desserts/show.html.erb
<br>
<br>
<h1><%=@dessert.name%></h1><br><br>

<image class="show" src="<%=(url_for(@dessert.photo))%>"><br><br>
<h2>Current Favorites: <%=@dessert.favorite_desserts.length%></h2>

<h1><%=link_to "Recipe", @dessert.recipe, target: :_blank%></h1>
<br>

<% if @fav_dessert.dessert_id==@dessert.id%>
    <h1> Yummm This is your Favorite Dessert! </h1><br>
<% else %> 
    <%= render "favorite"%>
<% end%>

app/views/desserts/top_ten.html.erb
<br>
<br>
<h1>Top Ten Desserts</h1>
<br>
<br>


<div class="row">
<div class="column">
<ol>
<% @top_five.each do |dessert|%>
    <li class="bite">
    <image class="top" src="<%=(url_for(dessert.photo))%>">
    <h3><%=dessert.name%></h3>
    <p><%="#{dessert.number_of_favorites} favorites!!!"%></p>
    <p><%= link_to "See #{dessert.name}", dessert_path(dessert)%></p><br><br><br><br>
    </li>
<%end%>
</ol>
</div>
<div class="column">
<% if Dessert.top_ten.length >5%>
    <ol start="6">
    <% @second_five.each do |dessert|%>
        <li class="bite">
        <image class="top" src="<%=(url_for(dessert.photo))%>">
        <h3><%=dessert.name%></h3>
        <p><%="#{dessert.number_of_favorites} favorites!!!"%></p>
        <p><%= link_to "See #{dessert.name}", dessert_path(dessert)%></p><br><br><br><br>
        </li>
    <%end%>
    </ol>
<%end%>
</div>
</div>