config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/login', to: 'sessions#new'
  resources :sessions, only: [:create]
  get '/logout', to: 'sessions#destroy'
  
  get '/', to: 'users#home', as: 'home'
  get '/desserts/top_ten', to: 'desserts#top_ten', as: 'top_ten_desserts'
  get '/meals/top_ten', to: 'meals#top_ten', as: 'top_ten_meals'
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :desserts
  resources :meals
  resources :favorite_desserts, only: [:create, :update]
  resources :favorite_meals, only: [:create, :update]
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BestBites</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
      <h1>Best Bites</h1><br>
      <div class="table">
      <ul>
        
      <% if !@current_user.nil? %>
        <li class="nav"><%=link_to "Home", home_path%></li>
        <li class="nav"><%=link_to "Profile", user_path(@current_user)%></li>
        <li class="nav"><%=link_to "Desserts", desserts_path%></li>
        <li class="nav"><%=link_to "Top-Ten", top_ten_desserts_path%></li>
        <li class="nav"><%=link_to "Meals", meals_path%></li>
        <li class="nav"><%=link_to "Top-Ten", top_ten_meals_path%></li>
        <li class="nav"><%=link_to "Logout", logout_path%></li>
      <% end %>
      </ul>
      </div>
  </header>
  <main>
    <%= yield %>
  </main>
  </body>
</html>